---
driver_config:
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  instance_type: <%= ENV['AWS_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids:  [ <%= ENV['AWS_SECURITY_GROUP_ID'] %> ]
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
  tags:
    created-by: test-kitchen
    Name: test-kitchen-cfncluster

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.3

platforms:
  - name: amazon_linux_2015_09_1
    driver_plugin: ec2
    driver_config:
      image_id: ami-f0091d91
    transport:
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: marketplace_centos_6_updates
    driver_plugin: ec2
    driver_config:
      image_id: ami-81d092b1
    transport:
      username: root
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: marketplace_centos_7_updates
    driver_plugin: ec2
    driver_config:
      image_id: ami-c7d092f7
    transport:
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: rhel_6-7_HVM_GA
    driver_plugin: ec2
    driver_config:
      image_id: ami-75f3f145
    transport:
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: rhel_7-1_HVM_GA
    driver_plugin: ec2
    driver_config:
      image_id: ami-4dbf9e7d
    transport:
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos_67_minimal_sriov
    driver_plugin: ec2
    driver_config:
      image_id: ami-c5a5bcf5
    transport:
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-14-04-lts
    driver_plugin: ec2
    driver_config:
      image_id: ami-3789b807
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: sles11
    driver_plugin: ec2
    driver_config:
      image_id: ami-3b0f420b
    transport:
      username: root
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: sles12
    driver_plugin: ec2
    driver_config:
      image_id: ami-d7450be7
    transport:
      username: root
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
