---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  flavor_id: <%= ENV['AWS_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUP_ID'] %>
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.2.1
  kitchen_root: /tmp/dougal

platforms:
  - name: amazon_linux_2015_03
    driver_plugin: ec2
    driver_config:
      image_id: ami-e7527ed7
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: marketplace_centos_6_updates
    driver_plugin: ec2
    driver_config:
      image_id: ami-81d092b1
      username: root
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: marketplace_centos_7_updates
    driver_plugin: ec2
    driver_config:
      image_id: ami-c7d092f7
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: rhel_6
    driver_plugin: ec2
    driver_config:
      image_id: ami-5fbcf36f
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: bashton_centos_6
    driver_plugin: ec2
    driver_config:
      image_id: ami-503bae60
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos_66_minimal_sriov
    driver_plugin: ec2
    driver_config:
      image_id: ami-45466e75
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: cfncluster-default-centos-66-minimal-sriov
    driver_plugin: ec2
    driver_config:
      image_id: ami-6dfbd25d
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
