---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.3

platforms:
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[cfncluster::default]
    attributes:

  - name: base_install
    run_list:
      - recipe[cfncluster::base_install]
    attributes:

  - name: sge_install
    run_list:
      - recipe[cfncluster::sge_install]
    attributes:

  - name: openlava_install
    run_list:
      - recipe[cfncluster::openlava_install]
    attributes:

  - name: torque_install
    run_list:
      - recipe[cfncluster::torque_install]
    attributes:

  - name: slurm_install
    run_list:
      - recipe[cfncluster::slurm_install]
    attributes:

  - name: base_config_MasterServer
    run_list:
      - recipe[cfncluster::base_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        cfn_volume: 'vol-f5845c34'
        cfn_region: 'us-west-2'

  - name: sge_config_MasterServer
    run_list:
      - recipe[cfncluster::sge_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        cfn_sqs_queue: 'cfncluster-chef'
        cfn_ddb_table: 'cfncluster-chef'
        cfn_volume: 'vol-f5845c34'
        cfn_region: 'us-west-2'

  - name: sge_config_CompeteFleet
    run_list:
      - recipe[cfncluster::sge_config]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        cfn_master: 'ip-192-168-0-38'
